pinmage/account/urls.py
from django.urls import path, include
from . import views

app_name = 'account'

urlpatterns = [
    path('follow/', views.user_follow, name='user_follow'),
    path('edit/', views.user_profile_edit, name='user_profile_edit'),
    path('<username>/', views.user_profile, name='user_profile'),
]

pinmage/pins/urls.py
from django.urls import path, include
from . import views

app_name = 'pins'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', views.pins_feed, name='pins_feed'),
    path('fetch/', views.fetch_suggestions, name='fetch_suggestions'),
    path('search/<slug:slug>/', views.search, name='search'),
    path('create/', views.pins_create, name='pins_create'),
    path('save/', views.pins_save, name='pins_save'),
    path('detail/<int:id>/<slug:slug>/', views.pins_detail, name='pins_detail'),
    path('comment/', views.pins_comment, name='pins_comment'),
]

pinmage/pins/models.py
from django.utils.text import slugify
from taggit.managers import TaggableManager
from django.conf import settings
from django.urls import reverse
from django.db import models

class Pin(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                            related_name='pin_created', 
                            on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    description = models.TextField(blank=True)
    # url = models.URLField(max_length=2000, null=True, blank=True)
    pin = models.ImageField(upload_to='images/%Y/%m/%d')
    created = models.DateTimeField(auto_now_add=True)
    tags = TaggableManager()
    users_saved = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='saved_pins',
                                        blank=True)       

    class Meta:
        indexes = [
            models.Index(fields=['-created']),
        ]
        ordering = ['-created']
    
    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('pins:pins_detail', args=[self.id, self.slug])


class Comment(models.Model):
    user = models.ForeignKey('auth.User', 
                            related_name='comments_on_pins',
                            on_delete=models.CASCADE)
    pin = models.ForeignKey(Pin,
                            related_name='comments',
                            on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        indexes = [
            models.Index(fields=['created'])
        ]
        ordering = ['created']

pinmage/pins/forms.py
from django.core.files.base import ContentFile
from django.utils.text import slugify
from .models import Pin
from django import forms
import requests

class PinCreateForm(forms.ModelForm):
    class Meta:
        model = Pin
        fields = ['title', 'description', 'tags', 'pin']

pinmage/pins/views.py
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils.text import slugify
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Count
from actions.models import Action
from actions.utils import create_action
from taggit.models import Tag
from django.http import JsonResponse, HttpResponse
from operator import attrgetter
from .models import Pin, Comment
from .forms import PinCreateForm
from django import forms
import requests, json

def get_notifications(request):
    actions = Action.objects.exclude(user=request.user)
    following_ids = request.user.profile.following.values_list('id', flat=True)
    # new_followers and new_pins
    if following_ids:
        notifications = actions.filter(target_id=request.user.id) | actions.filter(user_id__in=following_ids, verb='created a new pin')
    else:
        notifications = actions.filter(target_id=request.user.id)
    notifications = notifications.select_related('user', 'user__profile').prefetch_related('target')[:10]
    return notifications

"""
    1. user created and saved pins
    2. pins posted by people who user follows
    3. pins related to tags used by user or people who they follows
    4. pins related to user search (not yet implemented)
    To include all of above three criteria, it is possible to only query with tags
    i.e.user created and saved pins' tags,
        tags of pins created by people who user follows
        and then other pins related to above tags 
"""
@login_required
def pins_feed(request):
    user = request.user
    # tags of pins user created
    all_tags = [tag for pin in Pin.objects.filter(user_id=user.id) for tag in pin.tags.values_list('id', flat=True)]
    # tags of pins user saved
    all_tags += [tag for pin in user.saved_pins.all() for tag in pin.tags.values_list('id', flat=True)]

    # tags of pins created by people who user follows
    following_ids = user.profile.following.values_list('id', flat=True)
    if following_ids:
        all_tags += [tag for pin in Pin.objects.filter(user_id__in=following_ids) for tag in pin.tags.values_list('id', flat=True)]

    all_tags = list(set(all_tags))

    pins = Pin.objects.filter(tags__in=all_tags)
    pins = pins.annotate(same_tags=Count('tags')).order_by('-same_tags')
    pins = sorted(pins, key=attrgetter('created'), reverse=True)

    # to a new user who has no followers, following, created or saved pins
    # we have to show all pins
    if not pins or len(pins) < 100:
        pins = Pin.objects.all()

    paginator = Paginator(pins, 20)
    page = request.GET.get('page')
    # this means only new pins of new pages will be rendered
    pins_only = request.GET.get('pins_only')
    try:
        pins = paginator.page(page)
    except PageNotAnInteger:
        pins = paginator.page(1)
    except EmptyPage:
        if pins_only:
            return HttpResponse('')
        # the last page
        pins = paginator.page(paginator.num_pages)
    if pins_only:
        # new pins of new pages will be rendered in separate template and
        # will be included in main feed (pins_feed.html)
        return render(request, 'pins/pins_list_extension.html', {
            'pins': pins,
        })

    # to render the first time
    return render(request, 'pins/pins_feed.html', {
        'pins': pins,
        'notifications': get_notifications(request),
    })

# not finished yet
@login_required
def pins_create(request):
    error_message = None
    if request.method == 'POST':
        form = PinCreateForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            cd = form.cleaned_data
            new_pin = form.save(commit=False)
            new_pin.user = request.user
            new_pin.save()
            # Without this next line the tags won't be saved
            # this line is required for all many to many fields
            form.save_m2m()
            create_action(request.user, 'created a new pin', new_pin)
            return redirect(new_pin.get_absolute_url())
        else:
            # this is not the right way to validate form error
            # if you come back to upgrade the project,
            # make sure to catch potential form errors properly
            error_message = 'Make sure your file length is at most 100 characters!'
    return render(request, 'pins/pins_create.html', {
        'notifications': get_notifications(request),
        'error_message': error_message,
    })

@login_required
def pins_detail(request, id, slug):
    pin = Pin.objects.get(pk=id, slug=slug)
    comments = pin.comments.all()
    pin_tags_id = pin.tags.values_list('id', flat=True)
    similar_pins = Pin.objects.filter(tags__in=pin_tags_id)\
                            .exclude(id=id)
    similar_pins = similar_pins.annotate(same_tags=Count('tags'))\
                                .order_by('-same_tags')

    paginator = Paginator(similar_pins, 20)
    page = request.GET.get('page')
    # this means only new pins of new pages will be rendered
    pins_only = request.GET.get('pins_only')
    try:
        similar_pins = paginator.page(page)
    except PageNotAnInteger:
        similar_pins = paginator.page(1)
    except EmptyPage:
        if pins_only:
            return HttpResponse('')
        # the last page
        similar_pins = paginator.page(paginator.num_pages)
    if pins_only:
        # new pins of new pages will be rendered in separate template and
        # will be included in main feed (pins_feed.html)
        return render(request, 'pins/pins_list_extension.html', {
            'pins': similar_pins,
        })

    return render(request, 'pins/pins_detail.html', {
        'pin': pin,
        'comments': comments,
        'pins': similar_pins,
        'notifications': get_notifications(request),
    })

@login_required
@require_POST
def pins_save(request):
    # id and action are data-id and data-action (save, unsave) of <a> tag
    # when click, they are sent as form data
    pin_id = request.POST.get('id')
    user_action = request.POST.get('action')
    print(pin_id, user_action)
    if pin_id and user_action:
        try:
            pin = Pin.objects.get(id=pin_id)
            if user_action == 'save':
                pin.users_saved.add(request.user)
            else:
                pin.users_saved.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except Pin.DoesNotExist:
            pass
    return JsonResponse({'status': 'error'})

@require_POST
def pins_comment(request):
    pin_id = request.POST.get('pin_id')
    pin_comment = request.POST.get('pin_comment')
    try:
        pin = get_object_or_404(Pin, id=pin_id)
        Comment.objects.create(user=request.user, pin=pin, body=pin_comment)
        # parameters for pins_detail
        comments = pin.comments.all()
        pin_tags_id = pin.tags.values_list('id', flat=True)
        similar_pins = Pin.objects.filter(tags__in=pin_tags_id)\
                                .exclude(id=pin_id)
        similar_pins = similar_pins.annotate(same_tags=Count('tags'))\
                                    .order_by('-same_tags')
    except Pin.DoesNotExist:
        raise forms.ValidationError('Error')

    return render(request, 'pins/pins_detail.html', {
        'pin': pin,
        'comments': comments,
        'pins': similar_pins,
        'notifications': get_notifications(request),
    })

"""
    How to search
    1. search by request tag slug
    2. search by tags of pins which include request tag slug
    3. search by tags similar to reqeust tag slug (eg. 'aesthetic-girl' similar to 'aesthetic-girls')
"""
@login_required
def search(request, slug):
    all_tags = [slug]

    exact_pins_tags = [pin.tags.slugs() for pin in Pin.objects.filter(tags__slug__icontains=slug)]
    exact_pins_tags = [tag for tag_set in exact_pins_tags for tag in tag_set] # list comprehension does not work for some reasons

    similar_tags = [tag.slug for tag in Tag.objects.filter(slug__icontains=slug)]

    all_tags += exact_pins_tags + similar_tags

    pins = Pin.objects.filter(tags__slug__in=all_tags)
    pins = pins.annotate(same_tags=Count('tags')).order_by('-same_tags')

    paginator = Paginator(pins, 20)
    page = request.GET.get('page')
    pins_only = request.GET.get('pins_only')
    try:
        pins = paginator.page(page)
    except PageNotAnInteger:
        pins = paginator.page(1)
    except EmptyPage:
        if pins_only:
            return HttpResponse('')
        pins = paginator.page(paginator.num_pages)
    if pins_only:
        return render(request, 'pins/pins_list_extension.html', {
            'pins': pins,
        })
    # first time render
    return render(request, 'search/search_pins.html', {
        'pins': pins,
        'notifications': get_notifications(request),
    })

@login_required
def fetch_suggestions(request):
    if request.method == 'OPTIONS':
        tags_set = [{'value': tag.name, 'data': tag.slug} for tag in Tag.objects.all()]
        users_set = [{'value': user.username, 'data': user.username} for user in User.objects.all()]
        suggestions_set = tags_set + users_set
        return JsonResponse(json.dumps(suggestions_set), safe=False)

pinmage/pins/templates/pins/base.html
{% load static %}
<!-- {% load tailwind_tags %} -->
<!DOCTYPE html>
<html lang="en" class="scroll-smooth">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">
    
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/jquery.autocomplete.js' %}"></script> 
    <script src="{% static 'js/autosize.js' %}"></script>
    <script src="{% static 'js/js.cookie.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

    <title>{% block title %}{% endblock %}</title>
    {% block style %}{% endblock %}
    <link rel = "icon" href = "{% static 'images/logo.png' %}" type = "image/x-icon">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" type="text/css">
    <!-- {% tailwind_css %} -->
</head>

<body class="bg-gray-100 font-poppins m-0 p-0">
    <!-- Navigation bar -->
    <nav class="sticky px-3 md:px-6 py-2.5 w-full z-50 top-0 left-0 bg-gray-100 transition-all ease-in-out duration-300"
        id="nav_bar">
        <div class="flex items-center justify-between gap-2 md:gap-6">

            <div class="flex-none">
                <a href="{% url 'pins:pins_feed' %}" class="hover:bg-gray-300 rounded-full p-0.5 flex items-center">
                    <svg class="w-12 h-12" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
                        <path fill="#f2696a"
                            d="M19.369 21.695a6.505 6.505 0 0 0 .192-7.119l2.499-2.499a3.558 3.558 0 0 0 2.561-.068c.63-.265.746-1.12.263-1.603L21.58 7.103c-.484-.484-1.34-.367-1.605.265a3.56 3.56 0 0 0-.053 2.604l-2.483 2.483a6.505 6.505 0 0 0-7.119.192c-.501.349-.542 1.084-.11 1.516l7.643 7.643c.432.431 1.166.39 1.516-.111z" />
                        <path fill="#e2e2e2" d="m6.264 25.75 6.718-8.838 2.121 2.121z" />
                        <path fill="#1a4875"
                            d="m25.236 10.052-3.303-3.303a1.523 1.523 0 0 0-1.375-.416c-.479.094-.86.401-1.045.841a4.035 4.035 0 0 0-.162 2.661l-1.995 1.995a6.983 6.983 0 0 0-7.323.407 1.455 1.455 0 0 0-.616 1.07c-.04.45.12.891.438 1.209l2.454 2.454-6.444 8.479a.501.501 0 0 0 .398.802.505.505 0 0 0 .303-.102l8.479-6.444 2.454 2.454a1.514 1.514 0 0 0 1.209.438 1.454 1.454 0 0 0 1.07-.616 6.985 6.985 0 0 0 .407-7.323l2.014-2.014a4.026 4.026 0 0 0 2.615-.174c.439-.184.745-.564.839-1.043a1.524 1.524 0 0 0-.417-1.375zM8.881 23.133l4.143-5.451 1.308 1.308-5.451 4.143zm15.546-11.585a3.049 3.049 0 0 1-2.201.058.497.497 0 0 0-.52.118l-2.499 2.499a.5.5 0 0 0-.072.616 5.986 5.986 0 0 1-.177 6.571.456.456 0 0 1-.338.191.516.516 0 0 1-.414-.149l-2.71-2.71c-.015-.02-.022-.044-.04-.062l-2.121-2.121c-.018-.018-.042-.025-.062-.04l-2.71-2.71a.518.518 0 0 1-.149-.414.455.455 0 0 1 .191-.338 5.967 5.967 0 0 1 3.417-1.073c1.09 0 2.184.298 3.153.896a.501.501 0 0 0 .616-.072l2.483-2.482a.5.5 0 0 0 .116-.526 3.046 3.046 0 0 1 .044-2.238.42.42 0 0 1 .316-.247.53.53 0 0 1 .475.142l3.303 3.303a.534.534 0 0 1 .143.475.413.413 0 0 1-.244.313z" />
                    </svg>
                </a>
            </div>

            <div class="flex-grow items-center">
                <div class="relative w-full max-h-max">
                    <!-- search text input -->
                    <input id="autocomplete_input" type="text" autocomplete="off"
                        class="z-10 absolute inset-y-0 top-0 w-full p-3 pl-10 text-base font-medium text-gray-500 border border-gray-300 rounded-full bg-transparent focus:ring-blue-500 focus:border-blue-500"
                        placeholder="Search">
                    <!-- search text hint shadow -->
                    <input id="autocomplete_input_hint" type="text" autocomplete="off"
                        class="aboslute inset-y-0 top-0 w-full p-3 pl-10 text-base font-medium text-gray-700/50 border border-gray-300 rounded-full bg-neutral-300">
                    <!-- search icon -->
                    <div class="z-10 absolute inset-y-0 top-0 flex items-center pl-3 pointer-events-none">
                        <svg aria-hidden="true" class="w-5 h-5 text-gray-400" fill="none" stroke="currentColor"
                            viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="3.8"
                                d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                        </svg>
                    </div>
                    <!-- autocomplete items container -->
                    <!-- 
                        Then devbridge-autocomplete generated html markup will be inserted into this container. 
                    -->
                </div>
            </div>

            <div class="flex-none">
                <a href="#" id="notification_switch" class="relative hover:bg-gray-300 rounded-full p-2 flex items-center">
                    <svg id="switch_one" class="w-8 h-8" id="Layer_1" style="enable-background:new 0 0 512 512;" version="1.1"
                        viewBox="0 0 512 512" width="512px" xml:space="preserve" xmlns="http://www.w3.org/2000/svg"
                        xmlns:xlink="http://www.w3.org/1999/xlink">
                        <g id="switch_two">
                            <path id="switch_three"
                                d="M381.7,225.9c0-97.6-52.5-130.8-101.6-138.2c0-0.5,0.1-1,0.1-1.6c0-12.3-10.9-22.1-24.2-22.1c-13.3,0-23.8,9.8-23.8,22.1   c0,0.6,0,1.1,0.1,1.6c-49.2,7.5-102,40.8-102,138.4c0,113.8-28.3,126-66.3,158h384C410.2,352,381.7,339.7,381.7,225.9z" />
                            <path id="switch_four" d="M256.2,448c26.8,0,48.8-19.9,51.7-43H204.5C207.3,428.1,229.4,448,256.2,448z" />
                        </g>
                    </svg>
                    <div id="switch_five" class="absolute w-3 h-3 bg-red-500 border-2 border-white rounded-full top-3.5 right-2.5"></div>
                </a>
            </div>
             
            <div id="logout_switch_main" class="flex-none">
                <a id="logout_switch_one" href="{{ request.user.profile.get_absolute_url }}" class="hover:bg-gray-300 rounded-full p-2 flex items-center">
                    <img id="logout_switch_two" class="w-10 h-10 rounded-full object-cover" src="{{ request.user.profile.photo.url }}" alt="baby one">
                </a>
            </div>
        </div>
    </nav>

    <!-- these can load to DOM later -->
    <!-- Notification drop down box -->
    <div id="notification_box" class="fixed z-30 right-4 w-full max-w-xs md:max-w-sm h-0 rounded-3xl bg-gray-100 drop-shadow-md overflow-y-scroll divide-y-2 transition-all duration-300 ease-in-out">
        <div class="px-5 py-6 font-medium text-center text-gray-500 bg-inherit rounded-t-3xl">
            What's new?
        </div>
        <div class="divide-y-2">
            {% for noti in notifications %}
                {% include 'actions/notification.html' %}
            {% endfor %}
        </div>
    </div>

    <!-- logout drop down box -->
    <div id="logout_box" class="fixed hidden z-30 right-6 rounded-3xl bg-gray-100 drop-shadow-md transition-all duration-300 ease-in-out px-5 py-5">
        <a href="{% url 'pins:logout' %}" class="">
            <div class="flex items-center justify-between gap-2 group">
                <span class="bg-gray-100 font-medium text-gray-500 group-hover:text-red-500">Logout</span>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 group-hover:text-red-500">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15m3 0l3-3m0 0l-3-3m3 3H9" />
                </svg>                  
            </div>
        </a>
    </div>

    <!-- Create pin floating icon -->
    <a href="{% url 'pins:pins_create' %}">
        <div class="fixed bottom-6 left-6 md:bottom-8 md:left-12 z-30 cursor-grabbing hover:scale-110 md:hover:scale-125 transition-all duration-300 ease-in-out">
            <div class="p-0.5 w-16 h-16 rounded-full bg-gray-100/50 hover:bg-gray-100/75 drop-shadow-xl flex items-center justify-center">
                <svg id="plus_btn" class="w-14 h-14" enable-background="new 0 0 50 50" height="50px" id="Layer_1" version="1.1" viewBox="0 0 50 50" width="50px" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                    <line fill="none" stroke="#CC3333" stroke-miterlimit="10" stroke-width="9" stroke-linecap="round" stroke-linejoint="bevel" x1="9" x2="41" y1="25" y2="25"/>
                    <line fill="none" stroke="#CC3333" stroke-miterlimit="10" stroke-width="9" stroke-linecap="round" stroke-linejoint="bevel" x1="25" x2="25" y1="9" y2="41"/>
                </svg>
            </div>
        </div>  
    </a>      

    {% block content %}
    {% endblock %}
    
    {% block script %}
    {% endblock %}

    <!-- live search bar js -->
    <script>
        // I have spent an incredible amount of time to make this work
        // So, dont forget to json.dumps() from server side, and
        // use |safe filter to turn &#x27 to space or quote, and
        // finally to convert to json objects
        const csrftoken = Cookies.get('csrftoken');
        const fetch_url = "{% url 'pins:fetch_suggestions' %}";
        var options = {
                method: 'OPTIONS',
                headers: {'X-CSRFToken': csrftoken},
                mode: 'same-origin',
            };
        // tag list and username list
        var suggestions_set = [];
        
        fetch(fetch_url, options)
        .then(response => response.json())
        .then(data => {
            data = JSON.parse(data);
            Object.entries(data).forEach(([key, value]) => {
                suggestions_set.push(value);
            });
        })

        $('#autocomplete_input').devbridgeAutocomplete({
            lookup: suggestions_set,
            lookupLimit: 8,
            maxHeight: 500,
            triggerSelectOnValidInput: true,
            onSelect: function (each_item) {
                // each_item refers to every item in search_set
                // when user select a search query, this function will redirect to appropriate location
                if (each_item.data.startsWith('@')) {
                    redirect_to_user_profile(each_item.data)
                } else {
                    redirect_to_pins_search(each_item.data)
                }
            },
            onHint: function (hint) {
                $('#autocomplete_input_hint').val(hint);
            },
            formatResult: function(each_item, current_value) {
                // current_value refers to characters having been typed by user until now
                if (each_item.value.startsWith('@')) {
                    return `
                        <svg style="width: 1rem; height: 1rem;" class="text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                            <path fill-rule="evenodd" d="M7.5 6a4.5 4.5 0 119 0 4.5 4.5 0 01-9 0zM3.751 20.105a8.25 8.25 0 0116.498 0 .75.75 0 01-.437.695A18.683 18.683 0 0112 22.5c-2.786 0-5.433-.608-7.812-1.7a.75.75 0 01-.437-.695z" clip-rule="evenodd" />
                        </svg>                                  
                        <span class="font-medium italic text-md text-gray-500">${each_item.value}</span>
                    `
                } else {
                    return `
                        <svg aria-hidden="true" style="width: 1rem; height: 1rem;" class="text-gray-400" fill="none" stroke="currentColor"
                            viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="3.8"
                                d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                        </svg>
                        <span class="font-medium italic text-md text-gray-500">${each_item.value}</span>
                    `
                }
            },
            lookupFilter: function(each_item, original_query, query_lowercase) {
                var re = new RegExp('\\b' + $.Autocomplete.utils.escapeRegExChars(query_lowercase), 'gi');
                return re.test(each_item.value);
            },
            
        });

        // onSelect redirections
        function redirect_to_pins_search(slug) {
            const url = "{% url 'pins:search' 'placeholder' %}".replace('placeholder', slug)
            window.location.href = url;
        }
        // these replace methods are not a nice way to make url
        // according to some django developers, they are vulnerable to HTML injection
        // if you are coming back to this project to upgrade, please consider to fix this hack
        function redirect_to_user_profile(username) {
            const url = "{% url 'account:user_profile' 'placeholder' %}".replace('placeholder', username);
            window.location.href = url;
        }
    </script>
</body>

</html>

pinmage/pins/templates/pins/pins_feed.html
{% extends 'pins/base.html' %}
{% load static %}

{% block title %}Pins Feed{% endblock %}

{% block style %}
    <style>
        /* to make pin feed invisible until it is fully loaded */
        #pins_feed {
            display: none;
        }
    </style>
{% endblock %}

{% block content %}
<!-- preloader container -->
<div class="preloader-container bg-gray-100">
    <div class="wrapper">
        <div class="box-wrap">
            <div class="box one"></div>
            <div class="box two"></div>
            <div class="box three"></div>
            <div class="box four"></div>
            <div class="box five"></div>
            <div class="box six"></div>
        </div>
    </div>
    <span class="preloader-text">Making your feed ready</span>
</div>

<!-- pins feed -->
<div id="pins_feed" class="mt-2 columns-2 sm:columns-3 md:columns-4 lg:columns-5 px-4 py-2 gap-4">
    {% include 'pins/pins_list_extension.html' %}
</div>
{% endblock %}

{% block script %}
    <script>
        // to close the preloader
        window.addEventListener('load', () => {
            setTimeout(() => {
                document.querySelector('.preloader-container').classList.add('preloader-finish');
                document.querySelector('#pins_feed').style.display = 'block';
            }, 2000);
        })

        document.addEventListener('DOMContentLoaded', () => {
            
            // make an infinite scroll
            var page = 1;
            var empty_page = false;
            var block_request = false;

            window.addEventListener('scroll', function(event) {
                var margin = document.body.clientHeight - window.innerHeight - 500;
                if (window.pageYOffset > margin && !empty_page && !block_request) {
                    block_request = true;
                    page += 1;

                    fetch('?pins_only=1&page=' + page)
                    .then(response => response.text())
                    .then(html => {
                        if (html === '') {
                            empty_page = true;
                        }
                        else {
                            var pins_feed = document.getElementById('pins_feed');
                            // html is the returned result of pins_list_extension.html
                            pins_feed.insertAdjacentHTML('beforeEnd', html);
                            block_request = false;
                        }
                    })
                }
            })

            // Launch scroll event
            const scroll_event = new Event('scroll');
            window.dispatchEvent(scroll_event);
        })
    </script>
{% endblock %}